[phases.setup]
nixPkgs = [
    "php82",
    "php82Extensions.pdo",
    "php82Extensions.pdo_mysql",
    "php82Extensions.gd",
    "php82Extensions.mbstring",
    "php82Extensions.xml",
    "php82Extensions.zip",
    "php82Extensions.fileinfo",
    "php82Extensions.tokenizer",
    "php82Extensions.ctype",
    "php82Extensions.curl",
    "composer",
    "nodejs_20",
    "npm"
]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader --no-interaction",
    "npm ci"
]

[phases.build]
cmds = [
    "npm run build",
    "php artisan view:cache"
]

[start]
cmd = "php artisan config:clear && php artisan migrate --force && php artisan storage:link && php artisan serve --host=0.0.0.0 --port=$PORT"